### ISSUE TITLE
Updates to Readme

### ISSUE THREAD

**Issue by bsteinbach112** [PCswanson/spincontrol#2]
Hello-

I just tried to set up a Spin turntable on a fresh install of the latest Raspbian release and had some feedback for the directions:

- Now that PI is not the default account name, a user may need to adjust the code to match the correct file locations.
- PySerial seems to already be installed automatically.
- My Spin was not showing up as a TTYUSB device, but rather as TTYACM0. I'm not sure what the difference is, but this tutorial helped me figure out what was going wrong: [Link](https://opensource.com/article/20/5/usb-port-raspberry-pi-python)

Thanks for all of your original work on this.
-Bill

**Comment by PCswanson** [comment]
Thank you Bill! I'm going to add your tips to the readme for now, until I have a chance to do a full update.
